### ISSUE TITLE
Leia not compatible with Chai@5

### ISSUE THREAD

**Issue by tobybellwood** [lando/leia#37]
Chai 5.0.0 is ESM-only (https://github.com/chaijs/chai/releases/tag/v5.0.0) - so the way that Leia creates the func.js files will need to be altered depending on the version of chai installed.

For now, I've pinned our one-liner to chai4, but it's probably something to look at
`yarn add leia-parser mocha chai@4 command-line-test`

**Comment by pirog** [comment]
@tobybellwood makes sense. i think we probably want to have leia write the test files using the version of chai it ships with as opposed to letting the user override it with their own.
